build: false

version: 0.1.{build}

configuration:
  - Debug

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMGE: Visual Studio 2015
      APPVEYOR_SAVE_CACHE_ON_ERROR: true
      #APPVEYOR_RDP_PASSWORD: Pa55w0rd!

#init:
#  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

#on_finish:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

cache:
  - C:\Program Files\WindowsPowerShell\Modules\PSScriptAnalyzer -> appveyor.yml
  - C:\Program Files\WindowsPowerShell\Modules\Pester -> appveyor.yml
  - C:\Program Files\WindowsPowerShell\Modules\PSFramework -> appveyor.yml
  - C:\Program Files\WindowsPowerShell\Modules\dbatools -> appveyor.yml

test_script:
  # Test with native PS version
  - ps: .\Tests\appveyor.pester.ps1 -IncludeCoverage

  # Results
  - ps: . .\Tests\appveyor.pester.ps1 -Finalize -IncludeCoverage