build: false

version: 0.1.{build}

configuration:
  - Debug

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMGE: Visual Studio 2015
      APPVEYOR_SAVE_CACHE_ON_ERROR: true

cache:
  - C:\Program Files\WindowsPowerShell\Modules\PSScriptAnalyzer -> appveyor.yml
  - C:\Program Files\WindowsPowerShell\Modules\Pester -> appveyor.yml
  - C:\Program Files\WindowsPowerShell\Modules\PSFramework -> appveyor.yml
  - C:\Program Files\WindowsPowerShell\Modules\dbatools -> appveyor.yml

test_script:
# Test with native PS version
  - ps: . .\Tests\appveyor.pester.ps1
# Test with PS version 3
  - ps: powershell.exe -executionpolicy bypass -noprofile -file .\Tests\appveyor.pester.ps1
# Finalize pass - collect and upload results
  - ps: . .\Tests\appveyor.pester.ps1 -Finalize