build: false

version: 0.1.{build}

cache:
  - C:\Program Files\WindowsPowerShell\Modules\PSScriptAnalyzer -> appveyor.yml
  - C:\Program Files\WindowsPowerShell\Modules\Pester -> appveyor.yml
  - C:\Program Files\WindowsPowerShell\Modules\PSFramework -> appveyor.yml
  - C:\Program Files\WindowsPowerShell\Modules\dbatools -> appveyor.yml

before_test:
  - ps: .\appveyor.setup.ps1

test_script:
# Test with native PS version
  - ps: . .\Tests\appveyor.pester.ps1
# Test with PS version 3
  - ps: powershell.exe -version 3.0 -executionpolicy bypass -noprofile -file .\Tests\appveyor.pester.ps1
# Finalize pass - collect and upload results
  - ps: . .\Tests\appveyor.pester.ps1 -Finalize